#!/usr/bin/env python3
"""Generate the three decisive-rerun notebooks (10, 11, 12).

Standalone from `scripts/build_notebooks.py` on purpose: notebooks 00-09 must
not be touched or regenerated by this script. See
`RCG_AGENT_IMPLEMENTATION_INSTRUCTIONS.md` for the full spec these notebooks
implement.

The HF token is a read-only token and is intentionally hardcoded into the
generated notebooks (same pattern as `scripts/build_notebooks.py`), read from
the gitignored `.env` at *build* time. `notebooks/*.ipynb` is gitignored
(see .gitignore) so these files are never pushed to GitHub. This script itself
never contains the literal token value.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NB = ROOT / "notebooks"


def _load_hf_token() -> str:
    """Read HF token from env or the gitignored .env (never hardcode in this file)."""
    tok = os.environ.get("HF_TOKEN", "")
    if not tok:
        env_file = ROOT / ".env"
        if env_file.exists():
            for line in env_file.read_text(encoding="utf-8").splitlines():
                if line.strip().startswith("HF_TOKEN="):
                    tok = line.split("=", 1)[1].strip().strip('"').strip("'")
                    break
    return tok


# HF token is read from the gitignored .env at build time and injected into the
# generated (also gitignored, never pushed) notebooks below. It is NEVER written
# into this committed script, so nothing here leaks to GitHub.
HF_TOKEN = _load_hf_token()


def md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(keepends=True)}


def code(text: str) -> dict:
    # Fail fast at build time on any syntax error instead of shipping a broken cell.
    compile(text, "<cell>", "exec")
    return {
        "cell_type": "code",
        "metadata": {},
        "source": text.strip("\n").splitlines(keepends=True),
        "outputs": [],
        "execution_count": None,
    }


def nb(*cells: dict) -> dict:
    numbered = []
    for i, cell in enumerate(cells):
        cell = dict(cell)
        cell["id"] = f"cell{i:02d}"
        numbered.append(cell)
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "cells": numbered,
    }


def write(name: str, notebook: dict) -> None:
    NB.mkdir(parents=True, exist_ok=True)
    path = NB / name
    path.write_text(json.dumps(notebook, indent=1), encoding="utf-8")
    print("wrote", path.relative_to(ROOT))


REPO_URL = "https://github.com/kaileh57/interpreting.git"


def header(title: str, blurb: str) -> str:
    return f"""# {title}

**Secret:** `HF_TOKEN` (read-only token, hardcoded below for convenience —
this notebook is gitignored and never pushed to GitHub). See [README](../README.md).

{blurb}

Run **all cells top to bottom.** Every artifact is written under
`runs/<run_id>/` (canonical) and copied to `results/` (convenience), then
synced to `MyDrive/rcg-bench/` if Drive is mounted.
"""


def setup_cell(notebook_slug: str, install_extras: str) -> str:
    return f"""
# Cell 1 -- setup. HF token is hardcoded below (read-only token, never pushed --
# this notebook is gitignored). Run first.
import os, sys, subprocess, platform
from pathlib import Path

os.environ["HF_TOKEN"] = "{HF_TOKEN}"  # read-only token
REPO_URL = "{REPO_URL}"


def _find_root():
    for base in [Path.cwd(), Path.cwd().parent, *Path.cwd().parents]:
        if (base / "src" / "rcg").exists():
            return base
    return None


root = _find_root()
if root is None:
    target = Path.cwd() / "interpreting"
    if not (target / "src" / "rcg").exists():
        subprocess.check_call(["git", "clone", "--depth", "1", REPO_URL, str(target)])
    root = target

os.chdir(root)
sys.path.insert(0, str(root / "src"))

if (root / ".git").exists():
    _pull = subprocess.run(
        ["git", "pull", "--ff-only"], cwd=root, capture_output=True, text=True, check=False
    )
    if _pull.returncode != 0:
        raise RuntimeError(
            "git pull --ff-only failed, so this notebook could be running against a "
            "STALE copy of the rcg library (this caused a real TypeError before -- "
            "we now fail loudly instead of silently continuing). Fix: on Colab, "
            "Runtime -> Disconnect and delete runtime, then rerun this cell for a "
            "clean clone. stdout: " + _pull.stdout + " stderr: " + _pull.stderr
        )
for _m in [m for m in list(sys.modules) if m == "rcg" or m.startswith("rcg.")]:
    del sys.modules[_m]

_hf_token = os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")

from rcg.notebook_utils import colab_bootstrap, mount_drive

colab_bootstrap(install=True, require_gpu=False, extras="{install_extras}")

import torch


def _repo_commit():
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=root, capture_output=True, text=True, check=False
        )
        return out.stdout.strip() if out.returncode == 0 else None
    except Exception:
        return None


drive_dir = mount_drive()
cuda = torch.cuda.is_available()
print("Notebook:", "{notebook_slug}")
print("Python:", platform.python_version())
print("torch:", torch.__version__)
print("CUDA available:", cuda)
print("GPU:", torch.cuda.get_device_name(0) if cuda else "none (CPU fallback)")
print("repo commit:", _repo_commit())
print("HF_TOKEN present:", bool(_hf_token))
if not cuda:
    print(
        "WARNING: running on CPU fallback -- this run will use a tiny model, "
        "not the paper-grade Gemma model. Manifests below record this."
    )
if drive_dir:
    print("Drive output:", drive_dir)
"""


# ---------------------------------------------------------------------------
# Notebook 10: decisive layer sweep
# ---------------------------------------------------------------------------

NB10_CELL2 = """
# Cell 2 -- imports, config, run context.
import json
import random

import pandas as pd

from rcg.pipeline.run_context import create_run_context, write_manifest
from rcg.tasks.generators import CITY_CHAIN, unique_latent_slot_examples
from rcg.tasks.task_io import stable_hash, task_to_dict, write_jsonl
from rcg.models.loader import ModelConfig, ModelLoader
from rcg.models.hooks import num_hidden_layers
from rcg.notebook_utils import pick_model_id

MODEL_ID_REQUESTED = os.environ.get("RCG_MODEL_ID", "google/gemma-3-1b-it")
MODEL_ID = pick_model_id(MODEL_ID_REQUESTED)
CPU_FALLBACK_USED = MODEL_ID != MODEL_ID_REQUESTED
N_PER_SEED = int(os.environ.get("RCG_N_PER_SEED", "40"))
SEEDS = [int(x) for x in os.environ.get("RCG_SEEDS", "1,2,3").split(",")]
LAYER_FRACTIONS = [
    float(x) for x in os.environ.get("RCG_LAYER_FRACTIONS", "0.1,0.25,0.5,0.75,0.9").split(",")
]
CAUSAL_THRESHOLD = float(os.environ.get("RCG_CAUSAL_THRESHOLD", "0.5"))

ctx = create_run_context("10_experiment_decisive_layer_sweep", model_id=MODEL_ID)
print("run_id:", ctx.run_id)
print("run_dir:", ctx.run_dir)
print(f"model requested: {MODEL_ID_REQUESTED} | model used: {MODEL_ID} | cpu fallback: {CPU_FALLBACK_USED}")
print("N_PER_SEED:", N_PER_SEED, "SEEDS:", SEEDS, "LAYER_FRACTIONS:", LAYER_FRACTIONS)
"""

NB10_CELL3 = """
# Cell 3 -- load model.
loader = ModelLoader(
    ModelConfig(
        model_id=MODEL_ID,
        trust_remote_code=True,
        dtype="float32" if MODEL_ID == "gpt2" else "auto",
    )
)
model, tokenizer = loader.load()
N_LAYERS = num_hidden_layers(model)
print(f"Loaded {MODEL_ID} | layers = {N_LAYERS}")
"""

NB10_CELL4 = """
# Cell 4 -- generate balanced latent-slot tasks (city/currency family only).
VOCAB = [
    "Paris", "Tokyo", "Cairo", "Lima",
    "France", "Japan", "Egypt", "Peru",
    "euro", "yen", "pound", "sol",
]

tasks = unique_latent_slot_examples(N_PER_SEED, SEEDS, task_family="latent_slot_city_currency")
assert len({t.example_id for t in tasks}) == len(tasks), "example_id collision detected"

id_to_task = {t.example_id: t for t in tasks}
task_rows = []
for t in tasks:
    seed = int(t.example_id.split("_seed")[1][:3])
    task_rows.append(
        task_to_dict(t, seed=seed, index=0, task_family="latent_slot_city_currency", model_id=MODEL_ID)
    )
id_to_seed = {r["example_id"]: r["seed"] for r in task_rows}

write_jsonl(ctx.tasks_path, task_rows)
print(f"{len(tasks)} tasks across seeds {SEEDS} written to {ctx.tasks_path}")
"""

NB10_CELL5 = """
# Cell 5 -- build readouts once per candidate layer and score rank/reportability.
from rcg.interventions.layer_sweep import fraction_to_layer
from rcg.readouts.jlens import GradientJLens, JLensReadout
from rcg.readouts.logit_lens import LogitLensReadout
from rcg.readouts.probes import ProbeReadout
from rcg.metrics.ranking import normalize_concept, rank_metrics

candidate_layers = sorted({fraction_to_layer(model, f) for f in LAYER_FRACTIONS})
print("candidate layers:", candidate_layers, "from fractions:", LAYER_FRACTIONS)

READOUT_METADATA_DEFAULTS = dict(
    run_id=ctx.run_id, notebook=ctx.notebook, created_at_utc=ctx.created_at_utc,
    repo_commit=ctx.repo_commit, model_id=MODEL_ID,
    model_family=MODEL_ID.split("/")[0] if "/" in MODEL_ID else MODEL_ID,
)

readout_rows = []
for layer in candidate_layers:
    layer_fraction = layer / max(1, N_LAYERS - 1)

    jlens = JLensReadout(model, tokenizer, layer, vocabulary=VOCAB)
    ll = LogitLensReadout(model, tokenizer, layer)

    gjlens = GradientJLens(model, tokenizer, layer)
    try:
        gjlens.build(VOCAB, [t.prompt for t in tasks[:4]])
        gjlens_error = None
    except Exception as exc:
        gjlens_error = str(exc)
        print(f"WARNING: GradientJLens.build failed at layer {layer}: {exc}")

    hidden_labels = [t.latent_variables["hidden_city"] for t in tasks]
    probe, probe_error = None, None
    if len(set(hidden_labels)) >= 2:
        try:
            probe = ProbeReadout(model, tokenizer, layer)
            probe.fit([t.prompt for t in tasks], hidden_labels, "hidden_city")
        except Exception as exc:
            probe, probe_error = None, str(exc)
    else:
        probe_error = "insufficient class diversity for probe (need >= 2 distinct hidden cities)"

    def _row(task, method_name, candidate_rank, reportability, topk_json, error):
        return {
            **READOUT_METADATA_DEFAULTS,
            "task_family": task.task_family,
            "example_id": task.example_id,
            "seed": id_to_seed.get(task.example_id),
            "layer": layer,
            "layer_fraction": layer_fraction,
            "intervention_type": None,
            "intervention_strength": None,
            "readout_method": method_name,
            "target_variable": "hidden_city",
            "candidate_concept": task.latent_variables["hidden_city"],
            "candidate_rank": candidate_rank,
            "is_ground_truth_candidate": True,
            "is_distractor_candidate": False,
            "reportability_score": reportability,
            "baseline_logit_diff": None,
            "patched_logit_diff": None,
            "patch_delta": None,
            "normalized_causal_effect": None,
            "causal_threshold": CAUSAL_THRESHOLD,
            "failure_mode": None,
            "readout_topk_json": topk_json,
            "prompt_hash": stable_hash(task.prompt),
            "clean_prompt_hash": stable_hash(task.clean_prompt or task.prompt),
            "corrupt_prompt_hash": stable_hash(task.corrupt_prompt or ""),
            "error": error,
        }

    methods = {"jlens_proxy": jlens.top_k, "logit_lens": ll.top_k}
    for task in tasks:
        target = task.latent_variables["hidden_city"]
        for method_name, fn in methods.items():
            try:
                items = fn(task.prompt, 10)
                rm = rank_metrics(items, target=target, k=10)
                error = None
            except Exception as exc:
                rm = rank_metrics([], target=target, k=10)
                error = str(exc)
            readout_rows.append(
                _row(task, method_name, rm["target_rank"], 1.0 if rm["target_in_topk"] else 0.0,
                     rm["topk_json"], error)
            )

        if gjlens_error:
            readout_rows.append(_row(task, "jlens_grad", None, 0.0, "[]", gjlens_error))
        else:
            try:
                items = gjlens.top_k(task.prompt, 10)
                rm = rank_metrics(items, target=target, k=10)
                readout_rows.append(
                    _row(task, "jlens_grad", rm["target_rank"], 1.0 if rm["target_in_topk"] else 0.0,
                         rm["topk_json"], None)
                )
            except Exception as exc:
                readout_rows.append(_row(task, "jlens_grad", None, 0.0, "[]", str(exc)))

        if probe is None:
            readout_rows.append(_row(task, "probe", None, 0.0, "[]", probe_error))
        else:
            try:
                pred = probe.predict(task.prompt, "hidden_city")
                hit = normalize_concept(pred.concept) == normalize_concept(target)
                topk_json = json.dumps([{"concept": pred.concept, "score": pred.score}])
                readout_rows.append(
                    _row(task, "probe", 1 if hit else 2, 1.0 if hit else 0.0, topk_json, None)
                )
            except Exception as exc:
                readout_rows.append(_row(task, "probe", None, 0.0, "[]", str(exc)))

    print(f"layer {layer} (frac {layer_fraction:.2f}): readouts done for {len(tasks)} tasks")

df_readouts = pd.DataFrame(readout_rows)
print(f"{len(df_readouts)} total readout rows")
"""

NB10_CELL6 = """
# Cell 6 -- residual patch layer sweep (clean hidden-city -> corrupt hidden-city).
from rcg.interventions.layer_sweep import LayerSweepConfig, run_residual_patch_layer_sweep

sweep_config = LayerSweepConfig(
    layer_fractions=tuple(LAYER_FRACTIONS), strengths=(1.0,), causal_threshold=CAUSAL_THRESHOLD
)
causal_rows_raw = run_residual_patch_layer_sweep(model, tokenizer, tasks, config=sweep_config)

causal_rows = []
for r in causal_rows_raw:
    task = id_to_task.get(r["example_id"])
    causal_rows.append(
        {
            **READOUT_METADATA_DEFAULTS,
            "task_family": task.task_family if task else None,
            "example_id": r["example_id"],
            "seed": id_to_seed.get(r["example_id"]),
            "layer": r["layer"],
            "layer_fraction": r["layer_fraction"],
            "intervention_type": r["intervention_type"],
            "intervention_strength": r["strength"],
            "target_variable": "hidden_city",
            "candidate_concept": task.latent_variables["hidden_city"] if task else None,
            "baseline_logit_diff": r["baseline_logit_diff"],
            "patched_logit_diff": r["patched_logit_diff"],
            "patch_delta": r["patch_delta"],
            "normalized_causal_effect": r["normalized_causal_effect"],
            "normalized_causal_effect_raw": r["normalized_causal_effect_raw"],
            "causal_threshold": CAUSAL_THRESHOLD,
            "is_causal": r["is_causal"],
            "error": r["error"],
        }
    )

df_causal = pd.DataFrame(causal_rows)
print(f"{len(df_causal)} causal rows ({len(tasks)} tasks x {len(candidate_layers)} layers)")
"""

NB10_CELL7 = """
# Cell 7 -- merge readouts with the causal sweep and classify failure modes.
merge_cols = df_causal[
    [
        "example_id", "layer", "baseline_logit_diff", "patched_logit_diff", "patch_delta",
        "normalized_causal_effect", "normalized_causal_effect_raw", "is_causal",
        "intervention_type", "intervention_strength",
    ]
]
df_merged = df_readouts.drop(
    columns=["baseline_logit_diff", "patched_logit_diff", "patch_delta", "normalized_causal_effect",
             "intervention_type", "intervention_strength"]
).merge(merge_cols, on=["example_id", "layer"], how="left")


def _failure_mode(row):
    if row.get("error"):
        return "error"
    readable = (row.get("reportability_score") or 0) >= 1.0
    ce = row.get("normalized_causal_effect")
    causal = ce is not None and ce >= CAUSAL_THRESHOLD
    if readable and causal:
        return "readable_and_causal"
    if readable and not causal:
        return "readable_only"
    if not readable and causal:
        return "causal_only"
    return "neither"


df_merged["failure_mode"] = df_merged.apply(_failure_mode, axis=1)
print(df_merged["failure_mode"].value_counts())
"""

NB10_CELL8 = """
# Cell 8 -- choose the preregistered best causal layer from CLEAN latent-slot
# residual-patch results only (never from readout performance).
layer_causal_means = df_causal.groupby("layer")["normalized_causal_effect"].mean()
BEST_LAYER = int(layer_causal_means.idxmax())
BEST_LAYER_FRACTION = BEST_LAYER / max(1, N_LAYERS - 1)
SELECTED_LAYER_BY = "max_mean_causal_effect_on_latent_slot"
print(f"Selected causal layer: {BEST_LAYER} (fraction {BEST_LAYER_FRACTION:.2f}) via {SELECTED_LAYER_BY}")
print(layer_causal_means)
"""

NB10_CELL9 = """
# Cell 9 -- summary tables and sanity report.
from rcg.analysis.bootstrap import bootstrap_mean_ci
from rcg.metrics.stats import chance_reportability
from rcg.pipeline.sanity import structured_sanity

layer_summary = (
    df_merged.groupby(["readout_method", "layer"])
    .agg(
        mean_reportability=("reportability_score", "mean"),
        mean_causal_effect=("normalized_causal_effect", "mean"),
        fraction_causal=("is_causal", "mean"),
        n=("example_id", "count"),
    )
    .reset_index()
)
print(layer_summary.to_string(index=False))

sel = df_merged[df_merged["layer"] == BEST_LAYER]
rcg_rows = []
for method, sub in sel.groupby("readout_method"):
    rep_mean, rep_lo, rep_hi = bootstrap_mean_ci(sub["reportability_score"].tolist())
    ce_vals = sub["normalized_causal_effect"].dropna().tolist()
    ce_mean, ce_lo, ce_hi = bootstrap_mean_ci(ce_vals) if ce_vals else (0.0, 0.0, 0.0)
    readable = sub["reportability_score"] >= 1.0
    causal = sub["normalized_causal_effect"] >= CAUSAL_THRESHOLD
    readable_only = float((readable & ~causal).mean())
    causal_only = float((~readable & causal).mean())
    readable_and_causal = float((readable & causal).mean())
    denom = readable_and_causal + readable_only
    causal_precision_given_readable = (readable_and_causal / denom) if denom > 0 else 0.0
    rcg_rows.append(
        {
            "readout_method": method,
            "mean_reportability": rep_mean, "reportability_ci_lo": rep_lo, "reportability_ci_hi": rep_hi,
            "mean_causal_effect": ce_mean, "causal_effect_ci_lo": ce_lo, "causal_effect_ci_hi": ce_hi,
            "mean_rcg": rep_mean - ce_mean,
            "readable_only_rate": readable_only,
            "causal_only_rate": causal_only,
            "readable_and_causal_rate": readable_and_causal,
            "causal_precision_given_readable": causal_precision_given_readable,
        }
    )
df_rcg_selected = pd.DataFrame(rcg_rows)
print(df_rcg_selected.to_string(index=False))

chance_rep = chance_reportability(len(VOCAB), 10)
sanity = structured_sanity(
    sel.to_dict("records"), chance_reportability=chance_rep, causal_threshold=CAUSAL_THRESHOLD
)
print(json.dumps(sanity, indent=2, default=str))
"""

NB10_CELL10 = """
# Cell 10 -- figures.
import matplotlib.pyplot as plt

layer_curve_df = (
    df_merged.groupby("layer")
    .agg(mean_reportability=("reportability_score", "mean"), mean_causal_effect=("normalized_causal_effect", "mean"))
    .reset_index()
    .sort_values("layer")
)
fig1, ax1 = plt.subplots(figsize=(7, 4))
ax1.plot(layer_curve_df["layer"], layer_curve_df["mean_reportability"], marker="o", label="reportability")
ax1.plot(layer_curve_df["layer"], layer_curve_df["mean_causal_effect"], marker="s", label="causal effect")
ax1.axvline(BEST_LAYER, color="gray", linestyle="--", label=f"selected layer {BEST_LAYER}")
ax1.set_xlabel("Layer"); ax1.set_ylabel("Score"); ax1.set_title("Exp 10: layer curve")
ax1.legend(); fig1.tight_layout()
fig1.savefig(ctx.figures_dir / "10_layer_curve.png", dpi=150)
plt.close(fig1)

fig2, ax2 = plt.subplots(figsize=(6, 5))
plot_sel = sel.dropna(subset=["reportability_score", "normalized_causal_effect"])
ax2.scatter(plot_sel["reportability_score"], plot_sel["normalized_causal_effect"], alpha=0.4)
ax2.axhline(CAUSAL_THRESHOLD, color="gray", linestyle="--")
ax2.axvline(0.5, color="gray", linestyle="--")
ax2.set_xlabel("Reportability"); ax2.set_ylabel("Normalized causal effect")
ax2.set_title(f"Exp 10: reportability vs causal @ layer {BEST_LAYER}")
fig2.tight_layout()
fig2.savefig(ctx.figures_dir / "10_reportability_vs_causal_selected_layer.png", dpi=150)
plt.close(fig2)

from rcg.metrics.gap import failure_mode_counts

counts = failure_mode_counts(sel["failure_mode"].tolist())
modes = ["readable_and_causal", "readable_only", "causal_only", "neither"]
fig3, ax3 = plt.subplots(figsize=(7, 4))
ax3.bar(modes, [counts.get(m, 0) for m in modes], color=["#2ecc71", "#f39c12", "#3498db", "#95a5a6"])
ax3.set_title(f"Exp 10: failure modes @ layer {BEST_LAYER}")
ax3.tick_params(axis="x", rotation=20)
fig3.tight_layout()
fig3.savefig(ctx.figures_dir / "10_failure_mode_matrix_selected_layer.png", dpi=150)
plt.close(fig3)
print("figures saved to", ctx.figures_dir)
"""

NB10_CELL11 = """
# Cell 11 -- save artifacts and manifest.
import shutil

df_readouts.to_csv(ctx.results_dir / "10_layer_sweep_readouts.csv", index=False)
df_causal.to_csv(ctx.results_dir / "10_layer_sweep_causal.csv", index=False)
df_merged.to_csv(ctx.results_dir / "10_layer_sweep_merged.csv", index=False)

summary_payload = {
    "layer_summary": layer_summary.to_dict("records"),
    "selected_layer_rcg_table": df_rcg_selected.to_dict("records"),
    "sanity": sanity,
}
with open(ctx.results_dir / "10_layer_sweep_summary.json", "w", encoding="utf-8") as f:
    json.dump(summary_payload, f, indent=2, default=str)

top_results = ctx.root / "results"
top_results.mkdir(parents=True, exist_ok=True)
for name in [
    "10_layer_sweep_readouts.csv", "10_layer_sweep_causal.csv",
    "10_layer_sweep_merged.csv", "10_layer_sweep_summary.json",
]:
    shutil.copy2(ctx.results_dir / name, top_results / name)

fraction_causal_selected = float(sel["is_causal"].mean()) if len(sel) else 0.0
best_readout_row = (
    max(rcg_rows, key=lambda r: r["causal_precision_given_readable"]) if rcg_rows else None
)

manifest_payload = {
    "model_id_requested": MODEL_ID_REQUESTED,
    "model_id_used": MODEL_ID,
    "cpu_fallback_used": CPU_FALLBACK_USED,
    "n_per_seed": N_PER_SEED,
    "seeds": SEEDS,
    "layer_fractions": LAYER_FRACTIONS,
    "candidate_layers": candidate_layers,
    "causal_threshold": CAUSAL_THRESHOLD,
    "selected_layer": BEST_LAYER,
    "selected_layer_fraction": BEST_LAYER_FRACTION,
    "selected_layer_by": SELECTED_LAYER_BY,
    "fraction_causal_at_selected_layer": fraction_causal_selected,
    "best_readout_by_causal_precision": best_readout_row["readout_method"] if best_readout_row else None,
    "sanity": sanity,
    "sanity_intervention_moves_logit": sanity["intervention_moves_logit"],
    "n_readout_rows": len(df_readouts),
    "n_causal_rows": len(df_causal),
    "n_merged_rows": len(df_merged),
    "tasks_path": str(ctx.tasks_path),
    "results_dir": str(ctx.results_dir),
    "figures_dir": str(ctx.figures_dir),
    "warnings": [],
}

frac_causal_by_layer = df_causal.groupby("layer")["is_causal"].mean()
if (frac_causal_by_layer < 0.10).all():
    manifest_payload["sanity_intervention_moves_logit"] = False
    manifest_payload["warnings"].append(
        "Fewer than 10% of clean latent-slot tasks exceeded the causal threshold at EVERY "
        "swept layer. Treat this run's causal findings as failed-intervention evidence, not "
        "positive causal signal."
    )

write_manifest(ctx, manifest_payload)

from rcg.notebook_utils import sync_to_drive

sync_to_drive(root=ctx.root, extra_dirs=[ctx.run_dir])

print("Run directory:", ctx.run_dir)
print(f"Selected layer: {BEST_LAYER} (fraction {BEST_LAYER_FRACTION:.2f})")
print("Fraction causal at selected layer:", round(fraction_causal_selected, 3))
print("Best readout by causal precision:", manifest_payload["best_readout_by_causal_precision"])
print("Passed intervention sanity:", manifest_payload["sanity_intervention_moves_logit"])
"""


def build_10() -> dict:
    return nb(
        md(
            header(
                "Experiment 10: Decisive Layer Sweep",
                "Fixes the biggest issue from the earlier tool-comparison run: a single "
                "mid-layer patch under-estimates causal effect. This notebook sweeps "
                "several layer fractions, measures reportability and causal effect "
                "*separately* at each, and preregisters the best causal layer using "
                "only the clean latent-slot intervention (never readout performance).",
            )
        ),
        code(setup_cell("10_experiment_decisive_layer_sweep", "[dev]")),
        code(NB10_CELL2),
        code(NB10_CELL3),
        code(NB10_CELL4),
        code(NB10_CELL5),
        code(NB10_CELL6),
        code(NB10_CELL7),
        code(NB10_CELL8),
        code(NB10_CELL9),
        code(NB10_CELL10),
        code(NB10_CELL11),
    )


# ---------------------------------------------------------------------------
# Notebook 11: distractor rank causality
# ---------------------------------------------------------------------------

NB11_CELL2 = """
# Cell 2 -- imports, config, run context.
import json
import random

import pandas as pd

from rcg.pipeline.run_context import create_run_context, write_manifest
from rcg.tasks.generators import CITY_CHAIN, distractor_pair_example, unique_latent_slot_examples
from rcg.tasks.task_io import stable_hash, task_to_dict, write_jsonl
from rcg.models.loader import ModelConfig, ModelLoader
from rcg.models.hooks import num_hidden_layers
from rcg.notebook_utils import pick_model_id
from rcg.metrics.ranking import normalize_concept, rank_metrics
from rcg.interventions.causal_effects import logit_diff, normalize_causal_effect
from rcg.interventions.layer_sweep import LayerSweepConfig, run_residual_patch_layer_sweep
from rcg.interventions.residual_patch import PatchConfig, ResidualPatcher
from rcg.analysis.bootstrap import bootstrap_mean_ci, paired_bootstrap_diff_ci

MODEL_ID_REQUESTED = os.environ.get("RCG_MODEL_ID", "google/gemma-3-1b-it")
MODEL_ID = pick_model_id(MODEL_ID_REQUESTED)
CPU_FALLBACK_USED = MODEL_ID != MODEL_ID_REQUESTED
N_PER_PAIR = int(os.environ.get("RCG_N_PER_PAIR", "12"))
SEEDS = [int(x) for x in os.environ.get("RCG_SEEDS", "1,2,3").split(",")]
SELECTED_LAYER_ENV = os.environ.get("RCG_SELECTED_LAYER")
CAUSAL_THRESHOLD = float(os.environ.get("RCG_CAUSAL_THRESHOLD", "0.5"))

ctx = create_run_context("11_experiment_distractor_rank_causality", model_id=MODEL_ID)
print("run_id:", ctx.run_id)
print("run_dir:", ctx.run_dir)
print(f"model requested: {MODEL_ID_REQUESTED} | model used: {MODEL_ID} | cpu fallback: {CPU_FALLBACK_USED}")
print("N_PER_PAIR:", N_PER_PAIR, "SEEDS:", SEEDS)
"""

NB11_CELL3 = """
# Cell 3 -- load model and select the causal layer.
loader = ModelLoader(
    ModelConfig(
        model_id=MODEL_ID,
        trust_remote_code=True,
        dtype="float32" if MODEL_ID == "gpt2" else "auto",
    )
)
model, tokenizer = loader.load()
N_LAYERS = num_hidden_layers(model)
print(f"Loaded {MODEL_ID} | layers = {N_LAYERS}")

if SELECTED_LAYER_ENV:
    SELECTED_LAYER = int(SELECTED_LAYER_ENV)
    SELECTED_LAYER_BY = "env_RCG_SELECTED_LAYER"
else:
    quick_tasks = unique_latent_slot_examples(20, [1], task_family="quick_layer_probe")
    quick_config = LayerSweepConfig(
        layer_fractions=(0.1, 0.25, 0.5, 0.75, 0.9), strengths=(1.0,), causal_threshold=CAUSAL_THRESHOLD
    )
    quick_rows = run_residual_patch_layer_sweep(model, tokenizer, quick_tasks, config=quick_config)
    df_quick = pd.DataFrame(quick_rows)
    layer_means = df_quick.groupby("layer")["normalized_causal_effect"].mean()
    SELECTED_LAYER = int(layer_means.idxmax())
    SELECTED_LAYER_BY = "max_mean_causal_effect_on_latent_slot_quick_sweep"

SELECTED_LAYER_FRACTION = SELECTED_LAYER / max(1, N_LAYERS - 1)
print(f"Selected layer: {SELECTED_LAYER} (fraction {SELECTED_LAYER_FRACTION:.2f}) via {SELECTED_LAYER_BY}")
"""

NB11_CELL4 = """
# Cell 4 -- balanced distractor task generation across ALL ordered city pairs
# (not only Tokyo-hidden / Paris-distractor).
CITIES = ["Paris", "Tokyo", "Cairo", "Lima"]
PAIRS = [(h, d) for h in CITIES for d in CITIES if h != d]
print(f"{len(PAIRS)} ordered city pairs: {PAIRS}")

tasks = []
task_rows = []
for seed in SEEDS:
    for hidden_city, distractor_city in PAIRS:
        for i in range(N_PER_PAIR):
            task = distractor_pair_example(hidden_city, distractor_city, seed=seed, index=i)
            tasks.append(task)
            task_rows.append(
                task_to_dict(task, seed=seed, index=i, task_family="distractor_city_currency", model_id=MODEL_ID)
            )

assert len({t.example_id for t in tasks}) == len(tasks), "example_id collision detected"
id_to_task = {t.example_id: t for t in tasks}
id_to_seed = {r["example_id"]: r["seed"] for r in task_rows}
write_jsonl(ctx.tasks_path, task_rows)
print(f"{len(tasks)} distractor tasks across {len(PAIRS)} pairs x {len(SEEDS)} seeds -> {ctx.tasks_path}")
"""

NB11_CELL5 = """
# Cell 5 -- readout rank evaluation at the selected layer.
from rcg.readouts.jlens import GradientJLens, JLensReadout
from rcg.readouts.logit_lens import LogitLensReadout
from rcg.readouts.probes import ProbeReadout

VOCAB = [
    "Paris", "Tokyo", "Cairo", "Lima",
    "France", "Japan", "Egypt", "Peru",
    "euro", "yen", "pound", "sol",
]

jlens = JLensReadout(model, tokenizer, SELECTED_LAYER, vocabulary=VOCAB)
ll = LogitLensReadout(model, tokenizer, SELECTED_LAYER)

gjlens = GradientJLens(model, tokenizer, SELECTED_LAYER)
try:
    gjlens.build(VOCAB, [t.prompt for t in tasks[:6]])
    gjlens_error = None
except Exception as exc:
    gjlens_error = str(exc)
    print("WARNING: GradientJLens.build failed:", exc)

hidden_labels = [t.latent_variables["hidden_city"] for t in tasks]
probe, probe_error = None, None
if len(set(hidden_labels)) >= 2:
    try:
        probe = ProbeReadout(model, tokenizer, SELECTED_LAYER)
        probe.fit([t.prompt for t in tasks], hidden_labels, "hidden_city")
    except Exception as exc:
        probe, probe_error = None, str(exc)
else:
    probe_error = "insufficient class diversity for probe (need >= 2 distinct hidden cities)"

METADATA_DEFAULTS = dict(
    run_id=ctx.run_id, notebook=ctx.notebook, created_at_utc=ctx.created_at_utc,
    repo_commit=ctx.repo_commit, model_id=MODEL_ID,
    model_family=MODEL_ID.split("/")[0] if "/" in MODEL_ID else MODEL_ID,
)


def _readout_row(task, method_name, rm, error):
    return {
        **METADATA_DEFAULTS,
        "task_family": task.task_family,
        "example_id": task.example_id,
        "seed": id_to_seed.get(task.example_id),
        "layer": SELECTED_LAYER,
        "layer_fraction": SELECTED_LAYER_FRACTION,
        "readout_method": method_name,
        "target_variable": "hidden_city",
        "hidden_city": task.latent_variables["hidden_city"],
        "distractor_city": task.latent_variables["distractor_city"],
        "hidden_rank": rm["target_rank"],
        "hidden_score": rm["target_score"],
        "hidden_in_topk": rm["target_in_topk"],
        "distractor_rank": rm["distractor_rank"],
        "distractor_score": rm["distractor_score"],
        "distractor_in_topk": rm["distractor_in_topk"],
        "score_margin": rm["target_minus_distractor_score"],
        "rank_margin": (
            (rm["distractor_rank"] - rm["target_rank"])
            if (rm["distractor_rank"] is not None and rm["target_rank"] is not None)
            else None
        ),
        "readout_topk_json": rm["topk_json"],
        "prompt_hash": stable_hash(task.prompt),
        "clean_prompt_hash": stable_hash(task.clean_prompt or task.prompt),
        "corrupt_prompt_hash": stable_hash(task.corrupt_prompt or ""),
        "error": error,
    }


readout_rows = []
for task in tasks:
    hidden = task.latent_variables["hidden_city"]
    distractor = task.latent_variables["distractor_city"]

    for method_name, fn in (("jlens_proxy", jlens.top_k), ("logit_lens", ll.top_k)):
        try:
            items = fn(task.prompt, 10)
            rm = rank_metrics(items, target=hidden, distractor=distractor, k=10)
            readout_rows.append(_readout_row(task, method_name, rm, None))
        except Exception as exc:
            rm = rank_metrics([], target=hidden, distractor=distractor, k=10)
            readout_rows.append(_readout_row(task, method_name, rm, str(exc)))

    if gjlens_error:
        rm = rank_metrics([], target=hidden, distractor=distractor, k=10)
        readout_rows.append(_readout_row(task, "jlens_grad", rm, gjlens_error))
    else:
        try:
            items = gjlens.top_k(task.prompt, 10)
            rm = rank_metrics(items, target=hidden, distractor=distractor, k=10)
            readout_rows.append(_readout_row(task, "jlens_grad", rm, None))
        except Exception as exc:
            rm = rank_metrics([], target=hidden, distractor=distractor, k=10)
            readout_rows.append(_readout_row(task, "jlens_grad", rm, str(exc)))

    if probe is None:
        rm = rank_metrics([], target=hidden, distractor=distractor, k=10)
        readout_rows.append(_readout_row(task, "probe", rm, probe_error))
    else:
        try:
            pred = probe.predict(task.prompt, "hidden_city")
            hit_hidden = normalize_concept(pred.concept) == normalize_concept(hidden)
            hit_distractor = normalize_concept(pred.concept) == normalize_concept(distractor)
            rm = {
                "target_rank": 1 if hit_hidden else None,
                "target_score": pred.score if hit_hidden else None,
                "target_in_topk": hit_hidden,
                "distractor_rank": 1 if hit_distractor else None,
                "distractor_score": pred.score if hit_distractor else None,
                "distractor_in_topk": hit_distractor,
                "target_minus_distractor_score": None,
                "topk_json": json.dumps([{"concept": pred.concept, "score": pred.score}]),
            }
            readout_rows.append(_readout_row(task, "probe", rm, None))
        except Exception as exc:
            rm = rank_metrics([], target=hidden, distractor=distractor, k=10)
            readout_rows.append(_readout_row(task, "probe", rm, str(exc)))

df_readouts = pd.DataFrame(readout_rows)
print(f"{len(df_readouts)} readout rows ({len(tasks)} tasks x 4 methods)")
"""

NB11_CELL6 = """
# Cell 6 -- paired interventions: hidden (residual patch) vs distractor
# (string-replacement proxy, since the distractor is a literal prompt word).
patcher = ResidualPatcher(model, tokenizer)
pair_rows = []
for task in tasks:
    hidden = task.latent_variables["hidden_city"]
    distractor = task.latent_variables["distractor_city"]
    distractor_corrupt_city = task.latent_variables.get("distractor_corrupt_city")
    distractor_corrupt_prompt = task.latent_variables.get("distractor_corrupt_prompt")
    tm = task.target_metric
    error = None
    hidden_res = {"baseline": None, "patched": None, "delta": None}
    causal_hidden_raw = causal_hidden = None
    baseline_full = altered = distractor_delta = causal_distractor_raw = causal_distractor = None
    distractor_intervention_type = "unavailable"

    try:
        hidden_res = patcher.patch_and_measure(
            task.clean_prompt or task.prompt,
            task.corrupt_prompt or task.prompt,
            PatchConfig(layer=SELECTED_LAYER),
            tm.positive_token,
            tm.negative_token,
        )
        causal_hidden_raw = normalize_causal_effect(hidden_res["delta"], hidden_res["baseline"])
        causal_hidden = min(1.0, abs(causal_hidden_raw))

        baseline_full = logit_diff(model, tokenizer, task.prompt, tm.positive_token, tm.negative_token)
        if distractor_corrupt_prompt:
            altered = logit_diff(model, tokenizer, distractor_corrupt_prompt, tm.positive_token, tm.negative_token)
            distractor_delta = altered - baseline_full
            causal_distractor_raw = normalize_causal_effect(distractor_delta, baseline_full)
            causal_distractor = min(1.0, abs(causal_distractor_raw))
            distractor_intervention_type = "string_replacement_patch_proxy"
    except Exception as exc:
        error = str(exc)

    causal_diff = (
        (causal_hidden - causal_distractor)
        if (causal_hidden is not None and causal_distractor is not None)
        else None
    )
    causal_ratio = (
        (causal_hidden / max(causal_distractor, 1e-8))
        if (causal_hidden is not None and causal_distractor is not None)
        else None
    )

    pair_rows.append(
        {
            "run_id": ctx.run_id, "notebook": ctx.notebook, "created_at_utc": ctx.created_at_utc,
            "repo_commit": ctx.repo_commit, "model_id": MODEL_ID,
            "model_family": MODEL_ID.split("/")[0] if "/" in MODEL_ID else MODEL_ID,
            "task_family": task.task_family, "example_id": task.example_id,
            "seed": id_to_seed.get(task.example_id),
            "layer": SELECTED_LAYER, "layer_fraction": SELECTED_LAYER_FRACTION,
            "hidden_city": hidden, "distractor_city": distractor,
            "distractor_corrupt_city": distractor_corrupt_city,
            "hidden_intervention_type": "residual_patch",
            "distractor_intervention_type": distractor_intervention_type,
            "causal_threshold": CAUSAL_THRESHOLD,
            "baseline_logit_diff": hidden_res.get("baseline"),
            "hidden_patched_logit_diff": hidden_res.get("patched"),
            "hidden_patch_delta": hidden_res.get("delta"),
            "causal_hidden_raw": causal_hidden_raw, "causal_hidden": causal_hidden,
            "distractor_baseline_logit_diff": baseline_full,
            "distractor_altered_logit_diff": altered,
            "distractor_patch_delta": distractor_delta,
            "causal_distractor_raw": causal_distractor_raw, "causal_distractor": causal_distractor,
            "causal_diff": causal_diff, "causal_ratio": causal_ratio,
            "prompt_hash": stable_hash(task.prompt),
            "clean_prompt_hash": stable_hash(task.clean_prompt or task.prompt),
            "corrupt_prompt_hash": stable_hash(task.corrupt_prompt or ""),
            "error": error,
        }
    )

df_pairs = pd.DataFrame(pair_rows)
print(f"{len(df_pairs)} paired causal rows")
"""

NB11_CELL7 = """
# Cell 7 -- paired statistics.
valid = df_pairs.dropna(subset=["causal_hidden", "causal_distractor"])

hidden_mean, hidden_lo, hidden_hi = bootstrap_mean_ci(valid["causal_hidden"].tolist())
distractor_mean, distractor_lo, distractor_hi = bootstrap_mean_ci(valid["causal_distractor"].tolist())
diff_mean, diff_lo, diff_hi = paired_bootstrap_diff_ci(
    valid["causal_hidden"].tolist(), valid["causal_distractor"].tolist()
)
fraction_hidden_gt_distractor = float((valid["causal_hidden"] > valid["causal_distractor"]).mean()) if len(valid) else 0.0

fraction_hidden_in_topk = float(df_readouts["hidden_in_topk"].mean())
fraction_distractor_in_topk = float(df_readouts["distractor_in_topk"].mean())
fraction_both_readable = float((df_readouts["hidden_in_topk"] & df_readouts["distractor_in_topk"]).mean())

rank_based = df_readouts.dropna(subset=["hidden_rank", "distractor_rank"])
fraction_readout_ranks_hidden_above_distractor = (
    float((rank_based["hidden_rank"] < rank_based["distractor_rank"]).mean()) if len(rank_based) else None
)

margin_join = df_readouts.dropna(subset=["score_margin"]).merge(
    df_pairs[["example_id", "causal_diff"]].dropna(subset=["causal_diff"]), on="example_id", how="inner"
)
correlation_margin_vs_causal_diff = (
    float(margin_join["score_margin"].corr(margin_join["causal_diff"])) if len(margin_join) >= 2 else None
)

paired_stats = {
    "mean_causal_hidden": hidden_mean, "causal_hidden_ci": [hidden_lo, hidden_hi],
    "mean_causal_distractor": distractor_mean, "causal_distractor_ci": [distractor_lo, distractor_hi],
    "mean_paired_causal_diff": diff_mean, "paired_causal_diff_ci": [diff_lo, diff_hi],
    "fraction_hidden_gt_distractor": fraction_hidden_gt_distractor,
    "fraction_hidden_in_topk": fraction_hidden_in_topk,
    "fraction_distractor_in_topk": fraction_distractor_in_topk,
    "fraction_both_readable": fraction_both_readable,
    "fraction_readout_ranks_hidden_above_distractor": fraction_readout_ranks_hidden_above_distractor,
    "correlation_margin_vs_causal_diff": correlation_margin_vs_causal_diff,
    "n_paired_examples": int(len(valid)),
}
print(json.dumps(paired_stats, indent=2, default=str))
print(
    f"Readout detects both hidden and distractor concepts at rates {fraction_both_readable:.1%}, "
    f"but hidden intervention effect exceeds distractor effect by {diff_mean:.3f} "
    f"[{diff_lo:.3f}, {diff_hi:.3f}] in {fraction_hidden_gt_distractor:.1%} of examples."
)
"""

NB11_CELL8 = """
# Cell 8 -- case studies and figures.
import matplotlib.pyplot as plt

merged_case = df_readouts[df_readouts["readout_method"] != "probe"].merge(
    df_pairs[["example_id", "causal_hidden", "causal_distractor", "causal_diff"]], on="example_id", how="left"
)

case1 = merged_case[
    merged_case["distractor_rank"].notna() & merged_case["hidden_rank"].notna()
    & (merged_case["distractor_rank"] < merged_case["hidden_rank"])
    & (merged_case["causal_diff"] > 0.2)
].sort_values("causal_diff", ascending=False).head(3)

case2 = merged_case[
    merged_case["hidden_in_topk"] & merged_case["distractor_in_topk"]
    & (merged_case["causal_hidden"] >= CAUSAL_THRESHOLD) & (merged_case["causal_distractor"] < CAUSAL_THRESHOLD)
].sort_values("causal_diff", ascending=False).head(3)

case3 = merged_case[
    (~merged_case["hidden_in_topk"]) & (merged_case["causal_hidden"] >= CAUSAL_THRESHOLD)
].sort_values("causal_hidden", ascending=False).head(2)

case4 = merged_case[
    merged_case["distractor_in_topk"] & (merged_case["causal_distractor"].abs() < 0.1)
].sort_values("causal_distractor").head(2)

case_studies = {
    "distractor_ranked_above_hidden_but_hidden_more_causal": case1.to_dict("records"),
    "both_readable_but_only_hidden_causal": case2.to_dict("records"),
    "hidden_causal_but_unreadable": case3.to_dict("records"),
    "distractor_readable_but_causal_near_zero": case4.to_dict("records"),
}
with open(ctx.results_dir / "11_case_studies.json", "w", encoding="utf-8") as f:
    json.dump(case_studies, f, indent=2, default=str)

rank_valid = merged_case.dropna(subset=["rank_margin", "causal_diff"])
fig4, ax4 = plt.subplots(figsize=(6, 5))
if len(rank_valid):
    ax4.scatter(rank_valid["rank_margin"], rank_valid["causal_diff"], alpha=0.4)
ax4.axhline(0, color="gray", linestyle="--")
ax4.set_xlabel("Rank margin (distractor_rank - hidden_rank)")
ax4.set_ylabel("Causal diff (hidden - distractor)")
ax4.set_title("Exp 11: distractor rank margin vs causal difference")
fig4.tight_layout()
fig4.savefig(ctx.figures_dir / "11_distractor_rank_vs_causal_diff.png", dpi=150)
plt.close(fig4)

plot_pairs = df_pairs.dropna(subset=["causal_distractor", "causal_hidden"])
fig5, ax5 = plt.subplots(figsize=(6, 5))
if len(plot_pairs):
    ax5.scatter(plot_pairs["causal_distractor"], plot_pairs["causal_hidden"], alpha=0.4)
ax5.plot([0, 1], [0, 1], color="gray", linestyle="--")
ax5.set_xlabel("Distractor causal effect")
ax5.set_ylabel("Hidden causal effect")
ax5.set_title("Exp 11: hidden vs distractor causal effect")
fig5.tight_layout()
fig5.savefig(ctx.figures_dir / "11_hidden_vs_distractor_causal_effect.png", dpi=150)
plt.close(fig5)
print("saved case studies and figures")
"""

NB11_CELL9 = """
# Cell 9 -- save artifacts and manifest.
import shutil

df_readouts.to_csv(ctx.results_dir / "11_distractor_readouts.csv", index=False)
df_pairs.to_csv(ctx.results_dir / "11_distractor_causal_pairs.csv", index=False)

pair_cols_to_merge = [
    c for c in df_pairs.columns
    if c not in (
        "run_id", "notebook", "created_at_utc", "repo_commit", "model_id", "model_family",
        "task_family", "seed", "layer", "layer_fraction", "hidden_city", "distractor_city",
        "prompt_hash", "clean_prompt_hash", "corrupt_prompt_hash", "error",
    )
]
df_merged11 = df_readouts.merge(df_pairs[pair_cols_to_merge], on="example_id", how="left")
df_merged11.to_csv(ctx.results_dir / "11_distractor_merged.csv", index=False)

summary_payload = {
    "paired_stats": paired_stats,
    "case_study_counts": {k: len(v) for k, v in case_studies.items()},
}
with open(ctx.results_dir / "11_distractor_summary.json", "w", encoding="utf-8") as f:
    json.dump(summary_payload, f, indent=2, default=str)

top_results = ctx.root / "results"
top_results.mkdir(parents=True, exist_ok=True)
for name in [
    "11_distractor_readouts.csv", "11_distractor_causal_pairs.csv", "11_distractor_merged.csv",
    "11_distractor_summary.json", "11_case_studies.json",
]:
    src = ctx.results_dir / name
    if src.exists():
        shutil.copy2(src, top_results / name)

frac_causal_hidden = float((valid["causal_hidden"] >= CAUSAL_THRESHOLD).mean()) if len(valid) else 0.0
sanity_intervention_moves_logit = frac_causal_hidden >= 0.10
warnings = []
if not sanity_intervention_moves_logit:
    warnings.append(
        "Fewer than 10% of examples show a hidden-city causal effect above threshold at the "
        "selected layer. Treat this run as failed-intervention evidence."
    )

manifest_payload = {
    "model_id_requested": MODEL_ID_REQUESTED, "model_id_used": MODEL_ID,
    "cpu_fallback_used": CPU_FALLBACK_USED,
    "n_per_pair": N_PER_PAIR, "seeds": SEEDS, "n_pairs": len(PAIRS), "pairs": PAIRS,
    "selected_layer": SELECTED_LAYER, "selected_layer_fraction": SELECTED_LAYER_FRACTION,
    "selected_layer_by": SELECTED_LAYER_BY,
    "causal_threshold": CAUSAL_THRESHOLD,
    "paired_stats": paired_stats,
    "sanity_intervention_moves_logit": sanity_intervention_moves_logit,
    "n_readout_rows": len(df_readouts), "n_pair_rows": len(df_pairs),
    "tasks_path": str(ctx.tasks_path), "results_dir": str(ctx.results_dir), "figures_dir": str(ctx.figures_dir),
    "warnings": warnings,
}
write_manifest(ctx, manifest_payload)

from rcg.notebook_utils import sync_to_drive

sync_to_drive(root=ctx.root, extra_dirs=[ctx.run_dir])

fraction_distractor_outranks_but_hidden_more_causal = float(
    len(
        merged_case[
            merged_case["distractor_rank"].notna() & merged_case["hidden_rank"].notna()
            & (merged_case["distractor_rank"] < merged_case["hidden_rank"])
            & (merged_case["causal_diff"] > 0)
        ]
    )
    / max(1, len(merged_case))
)

print("Run directory:", ctx.run_dir)
print("Readout both-readable rate:", round(fraction_both_readable, 3))
print("Hidden > distractor causal fraction:", round(fraction_hidden_gt_distractor, 3))
print(f"Mean paired causal difference: {diff_mean:.3f} [{diff_lo:.3f}, {diff_hi:.3f}]")
print(
    "Fraction distractor outranks hidden but hidden more causal:",
    round(fraction_distractor_outranks_but_hidden_more_causal, 3),
)
"""


def build_11() -> dict:
    return nb(
        md(
            header(
                "Experiment 11: Distractor Rank Causality",
                "Turns the strongest prior signal into a decisive, balanced result: for "
                "every ordered (hidden, distractor) city pair, measure readout rank/margin "
                "AND a paired causal effect for both the hidden and the distractor variable. "
                "The prior run only tested Tokyo-hidden / Paris-distractor; this one is "
                "balanced across all 12 ordered pairs.",
            )
        ),
        code(setup_cell("11_experiment_distractor_rank_causality", "[dev]")),
        code(NB11_CELL2),
        code(NB11_CELL3),
        code(NB11_CELL4),
        code(NB11_CELL5),
        code(NB11_CELL6),
        code(NB11_CELL7),
        code(NB11_CELL8),
        code(NB11_CELL9),
    )


# ---------------------------------------------------------------------------
# Notebook 12: real AO and SAE baselines
# ---------------------------------------------------------------------------

NB12_CELL2 = """
# Cell 2 -- load model and build a small balanced task subset.
import json
import random

import pandas as pd

from rcg.pipeline.run_context import create_run_context, write_manifest
from rcg.tasks.generators import (
    CITY_CHAIN, distractor_pair_example, latent_slot_example, unique_latent_slot_examples,
)
from rcg.tasks.task_io import stable_hash, task_to_dict, write_jsonl
from rcg.models.loader import ModelConfig, ModelLoader
from rcg.models.hooks import capture_last_activation, middle_layer, num_hidden_layers
from rcg.notebook_utils import pick_model_id
from rcg.metrics.ranking import normalize_concept

MODEL_ID_REQUESTED = os.environ.get("RCG_MODEL_ID", "google/gemma-3-1b-it")
MODEL_ID = pick_model_id(MODEL_ID_REQUESTED)
CPU_FALLBACK_USED = MODEL_ID != MODEL_ID_REQUESTED
N_EXAMPLES = int(os.environ.get("RCG_N_EXAMPLES", "80"))
AO_CHECKPOINT = os.environ.get("RCG_AO_CHECKPOINT")
SAE_ARTIFACT = os.environ.get("RCG_SAE_MODEL_ID")

ctx = create_run_context("12_experiment_real_baselines_ao_sae", model_id=MODEL_ID)
print("run_id:", ctx.run_id)
print("run_dir:", ctx.run_dir)
print(f"model requested: {MODEL_ID_REQUESTED} | model used: {MODEL_ID} | cpu fallback: {CPU_FALLBACK_USED}")
print("AO_CHECKPOINT set:", bool(AO_CHECKPOINT), "| SAE_ARTIFACT set:", bool(SAE_ARTIFACT))

loader = ModelLoader(
    ModelConfig(
        model_id=MODEL_ID,
        trust_remote_code=True,
        dtype="float32" if MODEL_ID == "gpt2" else "auto",
    )
)
model, tokenizer = loader.load()
N_LAYERS = num_hidden_layers(model)
LAYER = middle_layer(model)
print(f"Loaded {MODEL_ID} | layers = {N_LAYERS} | layer = {LAYER}")

CITIES = ["Paris", "Tokyo", "Cairo", "Lima"]
rng = random.Random(7)
n_latent = N_EXAMPLES // 2
n_distractor = N_EXAMPLES - n_latent

tasks = unique_latent_slot_examples(n_latent, [7], task_family="latent_slot_city_currency")[:n_latent]
task_rows = [
    task_to_dict(t, seed=7, index=i, task_family="latent_slot_city_currency", model_id=MODEL_ID)
    for i, t in enumerate(tasks)
]
for i in range(n_distractor):
    hidden_city = rng.choice(CITIES)
    distractor_city = rng.choice([c for c in CITIES if c != hidden_city])
    task = distractor_pair_example(hidden_city, distractor_city, seed=7, index=i)
    tasks.append(task)
    task_rows.append(
        task_to_dict(task, seed=7, index=i, task_family="distractor_city_currency", model_id=MODEL_ID)
    )

assert len({t.example_id for t in tasks}) == len(tasks), "example_id collision detected"
write_jsonl(ctx.tasks_path, task_rows)
print(f"{len(tasks)} tasks written to {ctx.tasks_path}")
"""

NB12_CELL3 = """
# Cell 3 -- Activation Oracle status (never a silent fallback).
from rcg.readouts.activation_oracle_real import RealActivationOracleReadout

ao = RealActivationOracleReadout(model=model, tokenizer=tokenizer, checkpoint=AO_CHECKPOINT)
ao_status = ao.status()
print("Activation Oracle status:", ao_status)

ao_rows = []
if not ao_status.available:
    with open(ctx.results_dir / "12_activation_oracle_skipped.json", "w", encoding="utf-8") as f:
        json.dump(
            {"available": False, "reason": ao_status.reason, "checkpoint": ao_status.checkpoint}, f, indent=2
        )
    print("Activation Oracle skipped:", ao_status.reason)
else:
    question = "Which city is represented in this activation?"
    for task in tasks:
        hidden = task.latent_variables.get("hidden_city")
        distractor = task.latent_variables.get("distractor_city")
        try:
            act = capture_last_activation(model, tokenizer, task.prompt, LAYER)
            result = ao.query_forced_choice(act, question, choices=CITIES)
            correct = normalize_concept(result["concept"]) == normalize_concept(hidden)
            error = None
        except Exception as exc:
            result, correct, error = {"concept": None, "score": None}, False, str(exc)
        ao_rows.append(
            {
                "run_id": ctx.run_id, "notebook": ctx.notebook, "model_id": MODEL_ID,
                "example_id": task.example_id, "task_family": task.task_family, "layer": LAYER,
                "readout_method": "activation_oracle_forced_choice",
                "hidden_city": hidden, "distractor_city": distractor,
                "ao_answer": result.get("concept"), "ao_score": result.get("score"),
                "correct": correct, "error": error,
            }
        )
    df_ao = pd.DataFrame(ao_rows)
    df_ao.to_csv(ctx.results_dir / "12_activation_oracle_rows.csv", index=False)
    print(f"Activation Oracle ran on {len(df_ao)} examples; accuracy = {df_ao['correct'].mean():.3f}")
"""

NB12_CELL4 = """
# Cell 4 -- Gemma Scope / SAE status (never a silent fallback).
from rcg.readouts.gemma_scope_sae import GemmaScopeSAEReadout

sae = GemmaScopeSAEReadout(model=model, tokenizer=tokenizer, layer=LAYER, artifact_id=SAE_ARTIFACT)
sae_status = sae.status()
print("SAE status:", sae_status)

sae_rows = []
ablation_rows = []
if not sae_status.available:
    with open(ctx.results_dir / "12_sae_skipped.json", "w", encoding="utf-8") as f:
        json.dump(
            {"available": False, "reason": sae_status.reason, "artifact_id": sae_status.artifact_id}, f, indent=2
        )
    print("SAE skipped:", sae_status.reason)
else:
    for task in tasks:
        try:
            feats = sae.top_features(task.prompt, k=10)
            error = None
        except Exception as exc:
            feats, error = [], str(exc)
        if feats:
            for feat in feats:
                sae_rows.append(
                    {
                        "run_id": ctx.run_id, "notebook": ctx.notebook, "model_id": MODEL_ID,
                        "example_id": task.example_id, "layer": LAYER,
                        "readout_method": "sae_top_feature_readout",
                        "feature_id": feat["feature_id"], "activation": feat["activation"],
                        "description": feat["description"], "error": None,
                    }
                )
        else:
            sae_rows.append(
                {
                    "run_id": ctx.run_id, "notebook": ctx.notebook, "model_id": MODEL_ID,
                    "example_id": task.example_id, "layer": LAYER,
                    "readout_method": "sae_top_feature_readout",
                    "feature_id": None, "activation": None, "description": None, "error": error,
                }
            )

    for task in tasks[: min(5, len(tasks))]:
        tm = task.target_metric
        try:
            top = sae.top_features(task.prompt, k=1)
            res = (
                sae.ablate_and_measure(task.prompt, [top[0]["feature_id"]], tm.positive_token, tm.negative_token)
                if top
                else {"available": False, "reason": "no_top_feature"}
            )
        except Exception as exc:
            res = {"available": False, "reason": str(exc)}
        ablation_rows.append(
            {
                "run_id": ctx.run_id, "example_id": task.example_id, "layer": LAYER,
                "readout_method": "sae_feature_ablation" if res.get("available") else "sae_feature_ablation_not_available",
                **res,
            }
        )

    df_sae = pd.DataFrame(sae_rows)
    df_sae.to_csv(ctx.results_dir / "12_sae_rows.csv", index=False)
    if ablation_rows:
        pd.DataFrame(ablation_rows).to_csv(ctx.results_dir / "12_sae_ablation_rows.csv", index=False)
    print(f"SAE ran on {len(tasks)} examples; {len(df_sae)} feature rows, {len(ablation_rows)} ablation rows")
"""

NB12_CELL5 = """
# Cell 5 -- baseline comparison table (JLens/GradJLens/logit-lens/probe + AO/SAE if run).
from rcg.readouts.jlens import GradientJLens, JLensReadout
from rcg.readouts.logit_lens import LogitLensReadout
from rcg.readouts.probes import ProbeReadout
from rcg.metrics.ranking import rank_metrics

VOCAB = [
    "Paris", "Tokyo", "Cairo", "Lima",
    "France", "Japan", "Egypt", "Peru",
    "euro", "yen", "pound", "sol",
]

jlens = JLensReadout(model, tokenizer, LAYER, vocabulary=VOCAB)
ll = LogitLensReadout(model, tokenizer, LAYER)

gjlens = GradientJLens(model, tokenizer, LAYER)
try:
    gjlens.build(VOCAB, [t.prompt for t in tasks[:4]])
    gjlens_error = None
except Exception as exc:
    gjlens_error = str(exc)

hidden_labels = [t.latent_variables.get("hidden_city", "unknown") for t in tasks]
probe, probe_error = None, None
if len(set(hidden_labels)) >= 2:
    try:
        probe = ProbeReadout(model, tokenizer, LAYER)
        probe.fit([t.prompt for t in tasks], hidden_labels, "hidden_city")
    except Exception as exc:
        probe, probe_error = None, str(exc)
else:
    probe_error = "insufficient class diversity for probe"

comparison_rows = []
for task in tasks:
    hidden = task.latent_variables.get("hidden_city")
    for method_name, fn in (("jlens_proxy", jlens.top_k), ("logit_lens", ll.top_k)):
        try:
            items = fn(task.prompt, 10)
            rm = rank_metrics(items, target=hidden, k=10)
            rep, status = (1.0 if rm["target_in_topk"] else 0.0), "run"
        except Exception:
            rep, status = 0.0, "readout_only"
        comparison_rows.append(
            {"example_id": task.example_id, "readout_method": method_name, "reportability": rep,
             "causal_effect": None, "status": status}
        )

    if gjlens_error:
        rep, status = 0.0, "readout_only"
    else:
        try:
            items = gjlens.top_k(task.prompt, 10)
            rm = rank_metrics(items, target=hidden, k=10)
            rep, status = (1.0 if rm["target_in_topk"] else 0.0), "run"
        except Exception:
            rep, status = 0.0, "readout_only"
    comparison_rows.append(
        {"example_id": task.example_id, "readout_method": "jlens_grad", "reportability": rep,
         "causal_effect": None, "status": status}
    )

    if probe is None:
        rep, status = 0.0, "readout_only"
    else:
        try:
            pred = probe.predict(task.prompt, "hidden_city")
            rep = 1.0 if normalize_concept(pred.concept) == normalize_concept(hidden) else 0.0
            status = "run"
        except Exception:
            rep, status = 0.0, "readout_only"
    comparison_rows.append(
        {"example_id": task.example_id, "readout_method": "probe", "reportability": rep,
         "causal_effect": None, "status": status}
    )

if ao_status.available:
    for row in ao_rows:
        comparison_rows.append(
            {"example_id": row["example_id"], "readout_method": "activation_oracle_forced_choice",
             "reportability": 1.0 if row["correct"] else 0.0, "causal_effect": None, "status": "run"}
        )
else:
    comparison_rows.append(
        {"example_id": None, "readout_method": "activation_oracle_forced_choice",
         "reportability": None, "causal_effect": None, "status": "skipped"}
    )

if sae_status.available:
    comparison_rows.append(
        {"example_id": None, "readout_method": "sae_top_feature_readout",
         "reportability": None, "causal_effect": None, "status": "readout_only"}
    )
else:
    comparison_rows.append(
        {"example_id": None, "readout_method": "sae_top_feature_readout",
         "reportability": None, "causal_effect": None, "status": "skipped"}
    )

df_comparison = pd.DataFrame(comparison_rows)
comparison_summary = (
    df_comparison.groupby("readout_method")
    .agg(mean_reportability=("reportability", "mean"), status=("status", "first"), n=("example_id", "count"))
    .reset_index()
)
print(comparison_summary.to_string(index=False))
"""

NB12_CELL6 = """
# Cell 6 -- save artifacts and manifest.
import shutil

df_comparison.to_csv(ctx.results_dir / "12_baseline_comparison.csv", index=False)

baselines_summary = {
    "activation_oracle": {
        "available": ao_status.available, "reason": ao_status.reason, "checkpoint": ao_status.checkpoint,
        "n_examples": len(ao_rows) if ao_status.available else 0,
        "accuracy": (
            float(pd.DataFrame(ao_rows)["correct"].mean()) if ao_status.available and ao_rows else None
        ),
    },
    "sae": {
        "available": sae_status.available, "reason": sae_status.reason, "artifact_id": sae_status.artifact_id,
        "n_feature_rows": len(sae_rows) if sae_status.available else 0,
        "n_ablation_rows": len(ablation_rows) if sae_status.available else 0,
    },
    "comparison_summary": comparison_summary.to_dict("records"),
}
with open(ctx.results_dir / "12_baselines_summary.json", "w", encoding="utf-8") as f:
    json.dump(baselines_summary, f, indent=2, default=str)

top_results = ctx.root / "results"
top_results.mkdir(parents=True, exist_ok=True)
for name in ["12_baseline_comparison.csv", "12_baselines_summary.json"]:
    shutil.copy2(ctx.results_dir / name, top_results / name)
for optional_name in [
    "12_activation_oracle_rows.csv", "12_sae_rows.csv", "12_sae_ablation_rows.csv",
    "12_activation_oracle_skipped.json", "12_sae_skipped.json",
]:
    src = ctx.results_dir / optional_name
    if src.exists():
        shutil.copy2(src, top_results / optional_name)

manifest_payload = {
    "model_id_requested": MODEL_ID_REQUESTED, "model_id_used": MODEL_ID,
    "cpu_fallback_used": CPU_FALLBACK_USED,
    "n_examples": N_EXAMPLES, "layer": LAYER,
    "activation_oracle": baselines_summary["activation_oracle"],
    "sae": baselines_summary["sae"],
    "tasks_path": str(ctx.tasks_path), "results_dir": str(ctx.results_dir), "figures_dir": str(ctx.figures_dir),
}
write_manifest(ctx, manifest_payload)

from rcg.notebook_utils import sync_to_drive

sync_to_drive(root=ctx.root, extra_dirs=[ctx.run_dir])

ran = []
if ao_status.available:
    ran.append("activation_oracle")
if sae_status.available:
    ran.append("sae")
print("Run directory:", ctx.run_dir)
print("Baselines that truly ran:", ran if ran else "none (both skipped -- see manifest for reasons)")
"""


def build_12() -> dict:
    return nb(
        md(
            header(
                "Experiment 12: Real AO / SAE Baselines",
                "Adds real Activation Oracle and Gemma Scope SAE baseline hooks without "
                "overstating availability. If `RCG_AO_CHECKPOINT` / `RCG_SAE_MODEL_ID` "
                "aren't set (or the packages aren't installed), this notebook records an "
                "explicit skipped-baseline manifest and still produces a useful readout "
                "comparison table with the always-available methods.",
            )
        ),
        code(setup_cell("12_experiment_real_baselines_ao_sae", "[dev,sae]")),
        code(NB12_CELL2),
        code(NB12_CELL3),
        code(NB12_CELL4),
        code(NB12_CELL5),
        code(NB12_CELL6),
    )


if __name__ == "__main__":
    write("10_experiment_decisive_layer_sweep.ipynb", build_10())
    write("11_experiment_distractor_rank_causality.ipynb", build_11())
    write("12_experiment_real_baselines_ao_sae.ipynb", build_12())
